name: 1.0$(rev:.r)
trigger: none
pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'yarn install'
    displayName: Install

  # Test
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'yarn test'
    displayName: Test

  # Publish Test Results
  - task: PublishTestResults@2
    displayName: 'Publish Test Results junit.xml'
    inputs:
      testResultsFiles: junit.xml
      failTaskOnFailedTests: true

  # Publish code coverage
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage from $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
      failIfCoverageEmpty: true
