name: Test
on:
  push:
    branches:
      - master
      # - development

  pull_request:
    branches:
      - master
      - development

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node: ['14', '13', '12', '11', '10']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn install --ignore-engines

      - name: Test
        run: yarn test
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1

      - name: Build
        run: yarn build
        env:
          NEXT_TELEMETRY_DISABLED: 1
