name: Test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2
      - name: Install & Build & Test
        run: |
          yarn install --production=false
          yarn lint
          yarn test
        env:
          NODE_ENV: test
          CI: true
